[package]
name    = "luma"
version = "0.34.0"
edition = "2021"

[[bin]]
name = "luma"
path = "src/main.rs"

[profile.dev]
overflow-checks = false

[profile.release]
lto = true

[dependencies]
configparser = "3.0.2"
libc         = "0.2.146"
sdl2         = "0.35.2"
