# if !defined(LUMA__HEADER__MAIN)
# define LUMA__HEADER__MAIN
# define _ATFILE_SOURCE
# define _FORTIFY_SOURCE 2
# define _LARGEFILE_SOURCE
# define _LARGEFILE64_SOURCE
# define _ISOC99_SOURCE
# define _ISOC11_SOURCE
# define _ISOC2X_SOURCE
# define _POSIX_C_SOURCE 200809L
# define __STDC_WANT_IEC_60559_BFP_EXT__
# define __STDC_WANT_IEC_60559_FUNCS_EXT__
# define __STDC_WANT_IEC_60559_TYPES_EXT__
# define __STDC_WANT_LIB_EXT2__
# define _XOPEN_SOURCE
# deifne _XOPEN_SOURCE_EXTENDED
# endif
